#!/usr/bin/env node

'use strict';

var asciidocBlocksCheck = require('./');

if (process.argv.length < 2) {
    console.log('Usage: asciidoc-blocks-check + <filename.adoc>')
    process.exit(1);
}

var asciidoc = process.argv[1]

asciidocBlocksCheck(asciidoc)
